### ISSUE TITLE
Missing conversion error

### ISSUE THREAD

**Issue by Hunanbean** [steveway/papagayo-ng#19]
`Missing conversion for: ɻ
Traceback (most recent call last):
  File "O:\papagayo-ng-allosaurus\LipsyncFrameQT.py", line 432, in on_open
    self.open(file_path)
  File "O:\papagayo-ng-allosaurus\LipsyncFrameQT.py", line 468, in open
    self.doc.auto_recognize_phoneme()
  File "O:\papagayo-ng-allosaurus\LipsyncDoc.py", line 850, in auto_recognize_phoneme
    word.text = "".join(letter["phoneme"] for letter in word_chunk)
TypeError: sequence item 0: expected str instance, NoneType found`

I was finally able to give this a try. It looks very cool! I am not sure it is working as expected though. I was only able to get 1 sound file to work with it, and the auto breakdown was nothing near what i expected. It seemed the breakdown did not remotely match the spoken words. The sound file i was able to get recognized was of low quality though. That may be the issue.
Thanks!

**Comment by steveway** [comment]
If the result then is still not good can you send an example which I can test?
Because with the Papagayo Tutorial files, even the spanish ones, the results are really good.
(The conversion to other phonemesets is not good yet, so best keep it to CMU39 for now.)

**Comment by Hunanbean** [comment]
Audio files that would not load yesterday, when i was also having the false drag and drop problem, are loading today. I am retesting now.  I thought i had reloaded after the FFMPEG, but perhaps not.

Thank you

**Comment by Hunanbean** [comment]
Oh, that is so cool!!
I forgot that often times, i have to load, close, reload for the software to function properly after changes.
It is working now, and the error is gone with the fixes you implemented.
That is really impressive! seems at least 95%+ accuracy (just observation, not a full analysis).
Thank you so much for knowing how, and spending the time and effort to share this with us! It is sincerely appreciated. When this gets into the main version, i expect usage to skyrocket. I intend to post a video and start spreading the word again when this gets into main. Also, perhaps not the best place to discuss it, but it came to my attention that there are pre-compiled versions available to patreons? If this is infact the case, i will mention that in the video.
