### ISSUE TITLE
Perhaps expected: Drag and drop audio files is not functioning

### ISSUE THREAD

**Issue by Hunanbean** [steveway/papagayo-ng#20]
I do not know if it is just not in this version, but drag and drop to gui of audio files does not work.

Thank you

**Comment by Hunanbean** [comment]
Yes, the drag and drop is working today. I have no explanation as to what i may have done incorrectly.

Thank you

**Comment by Hunanbean** [comment]
Ok, i am having the problem again, but it is more involved. This is with the Allosaurus version, Installer release. I can only open one specific .wav file, and that is only if i open an existing project first, and it requests the audio file. 
The first thing i did was press download ffmpeg, it did that and told me to restart, which i did. I am however getting this message
`pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work`
I cannot seem to bring in any audio files, except one old .wav, the way described.
I have tested the audio files against the last version i am running from source (the first version with Allosaurus) and it works correctly.
Perhaps ffmpeg is not getting installed correctly on my system? I do not know.

Thank you

**Comment by Hunanbean** [comment]
Ok. It was probably a windows permission problem with writing to a the 'program files' folder. I manually downloaded a version of FFMPEG and copied ffmpeg.exe, ffplay.exe and ffprobe.exe into the Papagayo-NG root, where papagayo-ng.exe os. Now i can open audio files, but i cannot drag and drop them for some reason. If i start the program from an admin command line, it will not allow me to try, just a blocking icon. if I run the program through double clicking the program icon, it displays the proper icon, but does not actually work.

**Comment by Hunanbean** [comment]
The drag and drop issue was a windows permission problem. I installed it in a non-protected i.e. Not "program files" location and drag and drop is functioning perfectly.

Thank you. This is amazingly cool!

**Comment by steveway** [comment]
I've now changed it so that FFMpeg and the AI Model are saved in a User Directory.
That should prevent permission problems in the future.

**Comment by Hunanbean** [comment]
That worked well, thank you. The files download into the user folder, and both the ai model and ffmpeg work as expected. One suggestion, perhaps notify the user of where those files ended up.
