### ISSUE TITLE
Allosaurus requiring double download

### ISSUE THREAD

**Issue by Hunanbean** [steveway/papagayo-ng#25]
This may be specific to my system configuration, so possibly disregard if no one else reports the same issue. When you first install Papagayo-NG then press the install button for Allosaurus, it downloads and tells you to restart. When you restart, it flashes a message that says Allosaurus is not installed. So, you download again, and on this second restart, it works.

Thank you

p.s. I just wanted to say again, this is Super Cool!

**Comment by steveway** [comment]
Mhh, I hadn't had this happen before.
I created a new release.
Can you completely uninstall the old version and reinstall 1.6.3 and test that again?

**Comment by Hunanbean** [comment]
Appears to work fine in 1.6.3

Thank you
