### ISSUE TITLE
Request: Please correct a mistake i made. H should be HH

### ISSUE THREAD

**Issue by Hunanbean** [steveway/papagayo-ng#26]
It seems i made a mistake in naming the mouth shapes. I named a file H.png when it should be HH.png. This causes a missing mouth shape warning in Papagayo-NG.

My apologies.
The fix should be as simple as renaming H.png to HH.png in your source code, in both the 66% and the 100% folders. I have also updated my Git to correct the error.

Thank you

**Comment by Hunanbean** [comment]
It appears that you may have compensated for the incorrect naming at conversion level, so perhaps the fix is a bit more than just the rename. The warning can be seen when you breakdown an individual word, and mouse over the HH. In my local copy, i have made a copy of H and named it HH so it works at both levels.

**Comment by Hunanbean** [comment]
Any thoughts on this?

Be well

**Comment by steveway** [comment]
Hello  this is fixed: with https://github.com/steveway/papagayo-ng/commit/2ed5e06b1cde9794950f67b4f5ed47126bc215b4

**Comment by Hunanbean** [comment]
Thank you
