### ISSUE TITLE
Does not recognize previous installs location when installing updated version

### ISSUE THREAD

**Issue by Hunanbean** [steveway/papagayo-ng#31]
Hello. Installation of newer a version does not seem to automatically recognize previous installs location when installing updated version. For example, i have 1.6.4 installed in c:\software\papagayo-ng, but when installing this updated version 1.6.5, it automatically wants to put it in C:\Program Files (x86)\Papagayo-NG.

Thank you

**Comment by steveway** [comment]
This should behave like that now thanks to this change: https://github.com/steveway/papagayo-ng/commit/e04b624b73d68b82d996632c96a7d6e3f7b1a34a
I updated the installer in the 1.6.5 Release with this change and the change for the breakdown.

**Comment by Hunanbean** [comment]
Appears to be functioning properly, thank you
