### ISSUE TITLE
Add ability to download and switch between different Allosaurus pretrained models

### ISSUE THREAD

**Issue by T-oasterO-ven** [steveway/papagayo-ng#32]
I believe 1.6.5 uses the uni2005 model right (universal)?

If that is the case, there should be an ability to download and switch to language-specific models, which "should perform much better than the universal model" (Xinjian Li) for the said language.

Model eng2102 apparently does much better for English dialogue than latest/uni2005 according to the Allosaurus GitHub description.

If there is a way/workaround to use eng2102 in the current build (or does it already?) that I am unaware of please let me know.
Thanks for reading.

**Comment by steveway** [comment]
I didn't really see a difference in my tests.
But that is a good idea anyway!
I've added an option to the settings where you can type in the model you want.
If you change the model you will want to re-download it.
I've now moved all the download options to be permanently visible in the Toolbar under "Download".
For now you have to know yourself what options are available.
Currently it's "latest", "uni2005" and "eng2102".
In the future we might get a list of the options from Github similar to how we get the FFmpeg downloads internally.
