### ISSUE TITLE
Papagayo-NG 1.6.6 - New version issue with opening of mono .wav files or any audio file

### ISSUE THREAD

**Issue by T-oasterO-ven** [steveway/papagayo-ng#34]
When attempting to open an audio file nothing happens. Whereas in previous versions opening audio files worked flawlessly. The UI indicator also remains "stopped" the whole time.

**Comment by steveway** [comment]
Oh I see, I created the application again now.
Apparently the fix I thought was working to hide the console didn't change this at all.
So now during startup the console will appear, but it should load sound files correctly again if you re-download and re-install 1.6.6.
