### ISSUE TITLE
Installer error

### ISSUE THREAD

**Issue by romanbiz** [steveway/papagayo-ng#38]
Windows server 2016 64bit
[Papagayo-NG 1.6.6]

=== Verbose logging started: 29.03.2022  11:03:50  Build type: SHIP UNICODE 5.00.10011.00  Calling process: C:\Windows\system32\msiexec.exe ===
MSI (c) (E8:68) [11:03:50:365]: Font created.  Charset: Req=204, Ret=204, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (E8:68) [11:03:50:369]: Font created.  Charset: Req=204, Ret=204, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg

MSI (c) (E8:7C) [11:03:50:426]: MSI_DBG: Invalid descriptor format - unable to decode ProductCode in descriptor
MSI (c) (E8:70) [11:03:50:626]: Resetting cached policy values

MSI (c) (E8:70) [11:03:50:626]: Machine policy value 'Debug' is 0
MSI (c) (E8:70) [11:03:50:626]: ******* RunEngine:
           ******* Product: C:\Users\*****\Desktop\papa\papagayo-ng_installer.exe
           ******* Action: 
           ******* CommandLine: **********
MSI (c) (E8:70) [11:03:50:630]: Note: 1: 2203 2: C:\Users\*****\Desktop\papa\papagayo-ng_installer.exe 3: -2147286960 
MSI (c) (E8:70) [11:03:50:631]: MainEngineThread is returning 1620
=== Verbose logging stopped: 29.03.2022  11:03:50 ===

**Comment by steveway** [comment]
That is a quite unusual error, I haven't seen this before, what are the steps you use to receive that message?
Apparently from what I can find there are many different possible causes for getting this error.
Can you verify that the MD5 checksum of the installer program is: b28a898ae88b551cb03dcdfb438d5b3d
(I checked this checksum on Windows with this command:)
`CertUtil -hashfile .\papagayo-ng_installer.exe MD5`

**Comment by romanbiz** [comment]
> That is a quite unusual error, I haven't seen this before, what are the steps you use to receive that message? Apparently from what I can find there are many different possible causes for getting this error. Can you verify that the MD5 checksum of the installer program is: b28a898ae88b551cb03dcdfb438d5b3d (I checked this checksum on Windows with this command:) `CertUtil -hashfile .\papagayo-ng_installer.exe MD5`

Thanks for reply
MD5 checksum OK:
.\papagayo-ng_installer.exe:
b28a898ae88b551cb03dcdfb438d5b3d

Steps:

1. Downloaded the installer
2. Launched the installer as an administrator
3. nothing happened
4. Ran the installer through the command line and logged https://docs.microsoft.com/en-us/windows/win32/msi/standard-installer-command-line-options#log.
5. Got an error in the log

**Comment by romanbiz** [comment]
Solved. Install via command line
